add filter on admin ecosystem index
WildCodeSchool/orleans-php-202009-project-ideoz pull request #102
Opened 2021-01-07 11:46 UTC by AmelieRoussel

2021-01-07 12:38 UTC, damienchangenot submitted a review, later dismissed

2021-01-07 13:52 UTC, sblondeau requested changes

2021-01-07 13:52 UTC, sblondeau commented on assets/styles/adminEcosystem.scss
> +#ecosystem_status, #status_filter_status {
n'utiilse pas d'id pour le style, met des classes plutot

2021-01-07 13:52 UTC, sblondeau commented on src/Controller/AdminEcosystemController.php
> +            if ($statusName === 'All') {
c'est pas très propre le 'All' en dur
je te conseille : 
créé une constante STATUSES = [
                    'Client' => 'Client',
                    'Partenaire' => 'Partenaire',
                    'Adhérent' => 'Adhérent', 
];
 du coup dans le choiceType du peux direct appeler 
                 'choices'  => self::CHOICES
tu ajoute une option empty_data pour mettre le "tous"

ensuite ici dans ton controlleur, tu mets si !$statusName {
                 $ecosystems = $ecosystemRepository->findBy([], ['name' => 'ASC']); 
} else { ...}

2021-01-08 08:00 UTC, damienchangenot submitted a review, later dismissed

2021-01-08 08:49 UTC, sblondeau requested changes

2021-01-08 08:49 UTC, sblondeau commented on src/Controller/AdminEcosystemController.php
> +        if ($form->isSubmitted() && $form->isValid()) {
simplifiable je pense, par qq chose comme ça, qui t'évite un if
```
if ($form->isSubmitted() && $form->isValid()) { 
             if ($statusName) { 

                $status = $statusRepository->findOneBy(['name' => $statusName]);
                $ecosystems = $ecosystemRepository->findBy(['status' => $status], ['name' => 'ASC']); 
         }
}

$ecosystems ??= $ecosystemRepository->findBy([], ['name' => 'ASC']);

```

2021-01-08 12:46 UTC, AmelieRoussel commented on src/Controller/AdminEcosystemController.php
> +        if ($form->isSubmitted() && $form->isValid()) {
Beaucoup plus simple en effet, merci !

2021-01-08 12:58 UTC, damienchangenot approved these changes

2021-01-08 16:07 UTC, sblondeau approved these changes

2021-01-08 16:07 UTC, merged