Made the project part of collaborative space
WildCodeSchool/orleans-php-202009-project-ideoz pull request #141
Opened 2021-01-18 12:36 UTC by Gambino-stack

2021-01-18 13:56 UTC, AmelieRoussel submitted a review, later dismissed

2021-01-18 14:57 UTC, sblondeau requested changes

2021-01-18 14:57 UTC, sblondeau commented on src/Controller/CooperativeController.php
> +            'projects' => $projectRepository->findAll(),
y a pas un ORDER BY qqchose à mettre, (par date, nom ou autre ? )

2021-01-18 15:06 UTC, Gambino-stack commented on src/Controller/CooperativeController.php
> +            'projects' => $projectRepository->findAll(),
On peut les mettre par nom mais il y a pas de date , il faut en rajouter une ?

2021-01-19 07:59 UTC, damienchangenot approved these changes

2021-01-19 10:06 UTC, sblondeau approved these changes

2021-01-19 10:07 UTC, merged