delete competence
WildCodeSchool/orleans-php-202009-project-ideoz pull request #150
Opened 2021-01-19 14:45 UTC by damienchangenot

2021-01-19 14:47 UTC, AmelieRoussel submitted a review, later dismissed

2021-01-20 08:22 UTC, sblondeau requested changes

2021-01-20 08:22 UTC, sblondeau commented on src/Controller/CompetenceController.php
> +        $this->addFlash('danger', 'La compétence a bien été supprimé');
supprimée

2021-01-20 08:22 UTC, sblondeau commented on templates/adminCompetence/_delete_form.html.twig
> +<form method="post" action="{{ path('admin_competence_delete', {'id': competence.id}) }}" onsubmit="return confirm('Êtes-vous sur de vouloir supprimer cette compétence ?');">
sûr

2021-01-20 08:25 UTC, AmelieRoussel approved these changes

2021-01-20 08:28 UTC, sblondeau approved these changes

2021-01-20 08:28 UTC, merged