S03 us31 register form
WildCodeSchool/orleans-php-202009-project-ideoz pull request #151
Opened 2021-01-19 15:17 UTC by Flichyn

2021-01-19 15:29 UTC, AmelieRoussel submitted a review, later dismissed

2021-01-20 08:25 UTC, sblondeau requested changes

2021-01-20 08:25 UTC, sblondeau commented on src/Controller/RegistrationController.php
> +        $this->addFlash('success', 'Your email address has been verified.');
trad

2021-01-20 09:32 UTC, damienchangenot approved these changes

2021-01-20 12:22 UTC, merged