fiche entreprise + mailpour mise en relation
WildCodeSchool/orleans-php-202009-project-ideoz pull request #164
Opened 2021-01-21 16:45 UTC by damienchangenot

2021-01-21 16:54 UTC, AmelieRoussel submitted a review, later dismissed

2021-01-22 08:13 UTC, sblondeau requested changes

2021-01-22 08:13 UTC, sblondeau commented on src/Entity/User.php
> +        return (string) $this->username;
hum tu es sur que ça pose pas soucis de faire ça  ?
vous aviez pas fait en sorte que le login se fasse avec l'email et non avec le username ? 
j'ai peur que ça fasse planter le login si tu fais ça ?

2021-01-22 14:36 UTC, AmelieRoussel commented on src/Controller/CooperativeController.php
> +        dump($company);
reste un dump

2021-01-22 14:36 UTC, AmelieRoussel commented on src/Controller/CooperativeController.php
> +                'company' => $company
pourquoi ça a changé ?

2021-01-22 14:44 UTC, AmelieRoussel approved these changes

2021-01-22 15:54 UTC, sblondeau approved these changes

2021-01-22 15:54 UTC, merged