S07 us37 forgotten password
WildCodeSchool/orleans-php-202009-project-ideoz pull request #180
Opened 2021-01-23 23:42 UTC by Flichyn

2021-01-24 09:27 UTC, AmelieRoussel approved these changes, later dismissed

2021-01-24 14:08 UTC, sblondeau requested changes

2021-01-24 14:08 UTC, sblondeau commented on src/Controller/ResetPasswordController.php
> +            ->subject('Your password reset request')
trad

2021-01-24 14:08 UTC, sblondeau commented on src/Controller/ResetPasswordController.php
> +                'There was a problem validating your reset request - %s',
trad, verifie tous les messages flash

2021-01-24 14:18 UTC, AmelieRoussel approved these changes

2021-01-25 08:39 UTC, sblondeau approved these changes

2021-01-25 08:39 UTC, merged