create footer
WildCodeSchool/orleans-php-202009-project-ideoz pull request #19
Opened 2020-12-09 10:19 UTC by damienchangenot

2020-12-09 15:53 UTC, AmelieRoussel submitted a review, later dismissed

2020-12-10 10:23 UTC, sblondeau requested changes
manque des fixtures pour ta table company

2020-12-10 13:50 UTC, AmelieRoussel submitted a review, later dismissed

2020-12-10 14:45 UTC, sblondeau requested changes

2020-12-10 14:45 UTC, sblondeau commented on templates/_footer.html.twig
> +        <p class="mb-1">0661992159</p>
bah justement c'est pas sensé venir de ta table company ça ?

2020-12-10 14:45 UTC, sblondeau commented on src/DataFixtures/CompanyFixtures.php
> +        $company->setName($faker->word);
pour le nom tu peux mettre son nom et pas un faker, ça rendra meiux

2020-12-10 14:45 UTC, sblondeau commented on migrations/Version20201210133029.php
> +        // this down() migration is auto-generated, please modify it to your needs
tu as un pb de migrations. Si tu créé une table dans ta US, il me faut qu'un seul fichier de migration, là ça me drop client, parner et testimony car tu as pas remis à jour ta bdd entre les 2 PR.
ce fichier peut etre viré

2020-12-10 15:46 UTC, damienchangenot commented on templates/_footer.html.twig
> +        <p class="mb-1">0661992159</p>
ba je t'en ai parler par message justement vu qu'il faudrait l'afficher sur chaque page tu m'a dis de laisser de coté pour l'instant et de mettre en dur ^^

2020-12-10 16:13 UTC, Gambino-stack requested changes
Dans App.scss tu import "footer" au lieu de "footer.scss"

2020-12-10 23:01 UTC, sblondeau approved these changes, later dismissed

2020-12-11 07:57 UTC, merged