S00 initialization
WildCodeSchool/orleans-php-202009-project-ideoz pull request #2
Opened 2020-12-02 16:37 UTC by Flichyn

2020-12-02 18:12 UTC, AmelieRoussel submitted a review, later dismissed

2020-12-03 08:16 UTC, sblondeau requested changes

2020-12-03 08:16 UTC, sblondeau commented on templates/base.html.twig
> +    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;900&display=swap" rel="stylesheet">
tu as déjà fait un @import dans le fichier CSS pour Raleway. C'est soit le @import (qui importe une feuille de style), soit la balise link (qui importe aussi une feuille de style) mais pas les deux ;-)

2020-12-03 08:16 UTC, sblondeau commented on templates/base.html.twig
> +    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Raleway:wght@400;900&display=swap" rel="stylesheet">
et en plus tu rappelles Raleway avec Lato ici j'ai l'impression ! 
recommence sur Google Font, tu select tes 2 polices avec les graisses que tu veux, et une fois tout select tu choisi soit le @import soit le link

2020-12-03 08:21 UTC, Flichyn commented on templates/base.html.twig
> +    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;900&display=swap" rel="stylesheet">
Ah oui j'ai oublié de le retirer ! Mea culpa, je fais ça tout de suite :D

2020-12-03 09:36 UTC, Gambino-stack approved these changes
Ca m'as l'air ok 😊

2020-12-03 09:45 UTC, sblondeau approved these changes

2020-12-03 09:45 UTC, merged