Change redirection to error message
WildCodeSchool/orleans-php-202009-project-ideoz pull request #221
Opened 2021-01-26 17:29 UTC by Flichyn

2021-01-26 18:08 UTC, AmelieRoussel approved these changes, later dismissed

2021-01-27 07:56 UTC, sblondeau requested changes
pourquoi n'utilise tu pas @isGranted ?
ou même direct une config dans le security.yaml en protégeant /espace-cooz par ROLE_MEMBER ? 
ça t'éviterais beaucoup de lignes de code, et tu personnalise l'erreur 401 (qui est renvoyée si tu n'as pas les droits) ce qui te permet d'afficher une message pour dire qu'on a pas les droits

2021-01-27 10:30 UTC, AmelieRoussel approved these changes

2021-01-27 12:23 UTC, sblondeau approved these changes

2021-01-27 12:23 UTC, merged