Made the Navbar
WildCodeSchool/orleans-php-202009-project-ideoz pull request #23
Opened 2020-12-09 16:19 UTC by Gambino-stack

2020-12-09 18:08 UTC, damienchangenot submitted a review, later dismissed

2020-12-10 08:04 UTC, damienchangenot submitted a review, later dismissed

2020-12-10 10:31 UTC, sblondeau requested changes
CSS à simplifier (utiliser les variables pour surcharger les couleurs de base de bootstrap et mieux utiliser les classes, un btn ou une alert ne s'utilisent pas seuls.)
je te laisse modif partout où c'est nécessaire

2020-12-10 10:31 UTC, sblondeau commented on assets/styles/app.scss
> +        margin-top: 0;
un classe mt-xs-0 sur le body devrait faire l'affaire plutot que la media query

2020-12-10 10:31 UTC, sblondeau commented on assets/styles/app.scss
> +    background-color: $dark-second-color;
ça me parait compliqué 
pourquoi tu n'utilises pas plutot bg-dark sur ta navbar (qui a surcharger la couleur dark de base par ton $dark-second-color) ?

2020-12-10 10:31 UTC, sblondeau commented on assets/styles/app.scss
> +    background-color: $dark-second-color;
idem, les couleurs ne se gères pas sur btn, puisque tu associe btn à une autre classe qui elle contient la couleur

ça va te simplifier grandement ton css.

2020-12-10 10:31 UTC, sblondeau commented on assets/styles/app.scss
> +    background-color: $dark-second-color;
idem, tu as une classe alert-xxxx qui gère les couleurs en plus de alert

2020-12-10 10:31 UTC, sblondeau commented on templates/includes/_navbar.html.twig
> +                <a class="btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
et là btn btn-xxx

2020-12-10 11:45 UTC, Gambino-stack commented on assets/styles/app.scss
> +        margin-top: 0;
Ca ne marche pas sur le body quand je mets "<body class="mt-xs-0">" 😕

2020-12-10 13:56 UTC, AmelieRoussel commented on assets/styles/app.scss
> +    height: 50px;
les dimensions sont les mêmes que pour .navbar-brand, il vaudrait mieux mettre une variable plutôt que des valeurs en dur

2020-12-10 13:56 UTC, AmelieRoussel commented on templates/includes/_navbarmobile.html.twig
> +                <div class="text-light align-self-baseline">Connection</div>
connexion (connection c'est en anglais je crois)

2020-12-10 14:03 UTC, AmelieRoussel approved these changes

2020-12-10 16:44 UTC, sblondeau approved these changes

2020-12-10 16:44 UTC, merged