Us04 temoignage for homepage
WildCodeSchool/orleans-php-202009-project-ideoz pull request #30
Opened 2020-12-11 15:20 UTC by damienchangenot

2020-12-14 09:23 UTC, AmelieRoussel commented on assets/styles/app.scss
> +@import "home";
pas besoin d'importer le home.scss ici, c'est uniquement pour ce qui est commun à tout le site (donc navbar, footer, la mise en forme des h1 etc...)
le fichier home.scss existe déjà normalement et est chargé dans le bloc stylesheets de index normalement

2020-12-14 09:23 UTC, AmelieRoussel commented on assets/styles/home.scss
> +    max-width: 190px;
pas de valeurs en dur mais des variables

2020-12-14 09:23 UTC, AmelieRoussel commented on src/DataFixtures/EcosystemeFixtures.php
> +            $ecosystem->setLogo('https://via.placeholder.com/150');
c'est possible de charger des images directement avec faker il me semble non ?

2020-12-14 09:23 UTC, AmelieRoussel commented on migrations/Version20201210140511.php
> +        $this->addSql('CREATE TABLE ecosystem (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, logo VARCHAR(255) DEFAULT NULL, client_or_partner TINYINT(1) NOT NULL, activity VARCHAR(255)
client_or_partner n'est pas la bonne notation pour un booléen, ce serait plutôt is_client et dans ce cas précis je mettrais plutôt 'status' et en valeur soit client soit partenaire

2020-12-14 09:23 UTC, AmelieRoussel commented on templates/home/index.html.twig
> +        <h2 class="text-center my-5">Témoignages</h2>
retire le my-5, un margin va être appliqué à tous les h2 dans mon fix pour uniformiser ;)

2020-12-14 09:40 UTC, damienchangenot commented on src/DataFixtures/EcosystemeFixtures.php
> +            $ecosystem->setLogo('https://via.placeholder.com/150');
oui mais ça mettait 3 heure a charger ou ça les chargeait pas du tout, j'ai vu avec sylvain qui m'a dit de mettre un placeholder en fixture

2020-12-14 13:14 UTC, AmelieRoussel approved these changes, later dismissed

2020-12-15 08:19 UTC, sblondeau requested changes

2020-12-15 08:19 UTC, sblondeau commented on migrations/Version20201210140511.php
> +        $this->addSql('CREATE TABLE ecosystem (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, logo VARCHAR(255) DEFAULT NULL, client_or_partner TINYINT(1) NOT NULL, activity VARCHAR(255)
pas mieux ;-)

2020-12-15 08:19 UTC, sblondeau commented on migrations/Version20201210141352.php
> +        $this->addSql('CREATE TABLE testimonye (id INT AUTO_INCREMENT NOT NULL, ecosysteme_id INT NOT NULL, content LONGTEXT NOT NULL, UNIQUE INDEX UNIQ_9C54504D57ADEC91 (ecosysteme_id), PRIMARY KEY(
testimony par testimony**e**

2020-12-15 08:19 UTC, sblondeau commented on migrations/Version20201210153341.php
> +        // this up() migration is auto-generated, please modify it to your needs
tu ne devrais avoir qu'un fichier de migration (ou au pire un par entity créée)
vu que tu as des modif à faire sur les entity, je te conseille 
0. fais les modifs demandées sur les noms de tables/champs
1. supprimer ces qq fichiers de Migration que tu as générer
2. drop les tables de ta bdd
3. refais un d:m:m pour revenir à un état propre (sans les nouvelles tables)
4. génère la nouvelle migration avec make;migrations
5. refais un d:m:m pour mettre à jour ta database

2020-12-15 08:19 UTC, sblondeau commented on src/DataFixtures/TestimonyFixtures.php
> +        }$manager->flush();
manque un retour à la ligne

2020-12-15 08:19 UTC, sblondeau commented on src/Entity/Ecosystem.php
> +    private bool $status;
ah bah là aussi tu l'a changé en fait... bon  concentre toi sur le nettoyage des migrations

2020-12-15 08:19 UTC, sblondeau commented on templates/home/index.html.twig
> +        <div class="d-flex flex-wrap justify-content-around">
pourquoi ne pas utiliser le système de grid row/col de bootstrap plutot ?

2020-12-15 10:09 UTC, sblondeau approved these changes

2020-12-15 10:09 UTC, merged