add testimonies page
WildCodeSchool/orleans-php-202009-project-ideoz pull request #48
Opened 2020-12-16 13:22 UTC by Gambino-stack

2020-12-16 13:43 UTC, damienchangenot submitted a review, later dismissed

2020-12-17 09:08 UTC, sblondeau reviewed
images > 200ko, a reduire grandement

2020-12-17 09:09 UTC, sblondeau requested changes

2020-12-17 09:09 UTC, sblondeau commented on templates/testimonies/testimonies.html.twig
> +                <div class="col-12 col-sm-12 col-md-12 col-lg-12">
col-12 est inutile et le fait de mettre sm-12 md-12 lg--12 aussi car de base le col-12 par défaut s'applique aussi aux tailles plus grandes

2020-12-17 14:15 UTC, AmelieRoussel approved these changes

2020-12-18 08:23 UTC, sblondeau approved these changes

2020-12-18 08:23 UTC, merged