S03 us18 read ecosystem
WildCodeSchool/orleans-php-202009-project-ideoz pull request #72
Opened 2020-12-30 10:14 UTC by AmelieRoussel

2021-01-02 18:05 UTC, damienchangenot submitted a review, later dismissed

2021-01-04 07:59 UTC, sblondeau requested changes

2021-01-04 07:59 UTC, sblondeau commented on migrations/Version20201229113316.php
> +final class Version20201229113316 extends AbstractMigration
cette migration ne me semble pas nécessaire, ça drop un champ d'une table !
tu as du oublié de jouer les migrations au début de ton US

2021-01-04 07:59 UTC, sblondeau commented on src/Controller/HomeController.php
> +            'clients' => $ecosystemRepository->findBy(['status' => 1], ['id' => 'ASC'], 10),
ça correspond à quoi ce 1 et 2 ? c'est une clé étrangère ? faut pas que ce soit un id de bdd !
vaut mieux travailler avec des constante 
const CLIENT = 1 et const PARTNER=2

2021-01-04 07:59 UTC, sblondeau commented on src/DataFixtures/StatusFixtures.php
> +        'Client',
je suis plus trop le truc car là tu as une table avec des status... donc je pense qu'au dessus tu as du mettre des "id" ce qu'il ne faut pas faire !
il faut plus haut que tu récupères via une requete la ligne de bdd qui correspond à un client ou à un partenaire

2021-01-04 07:59 UTC, sblondeau commented on src/Entity/Ecosystem.php
> +     *     maxMessage="Le nom saisi {{ value }} est trop long, il ne devrait pas dépasser {{ limit }} caractères")
la traduction des message est inutile si tu passes Sf en français

2021-01-04 11:12 UTC, AmelieRoussel commented on migrations/Version20201229113316.php
> +final class Version20201229113316 extends AbstractMigration
En fait j'ai supprimé la champ statut parce que finalement notre client rajoute encore un statut donc j'ai trouvé ça plus pertinent de faire une table statut puis de mettre une clé étrangère dans ecosystème

2021-01-04 11:17 UTC, damienchangenot approved these changes, later dismissed

2021-01-04 16:01 UTC, sblondeau requested changes

2021-01-04 16:01 UTC, sblondeau commented on src/Controller/HomeController.php
> +        $client = $statusRepository->findBy(['name' => 'Client']);
je ferais plutot un findOneBy ici ?

2021-01-05 08:49 UTC, sblondeau approved these changes

2021-01-05 08:49 UTC, merged