Made contact form
WildCodeSchool/orleans-php-202009-project-ideoz pull request #89
Opened 2021-01-06 16:25 UTC by Flichyn

2021-01-06 16:33 UTC, AmelieRoussel submitted a review, later dismissed

2021-01-06 19:35 UTC, sblondeau requested changes

2021-01-06 19:35 UTC, sblondeau commented on src/Controller/ContactController.php
> +                ->to('xclamation@hotmail.fr')
ne doit pas etre une adresse en dur mais etre un paramètre (mail_admin par ex)

2021-01-06 19:35 UTC, sblondeau commented on src/Controller/ContactController.php
> +                ->from($this->getParameter('mailer_from'))
le mail est envoyé depuis un user vers l'admin c'est bien ça ? 
donc dans le from, mets plutot le $contact->getEmail()

2021-01-06 19:35 UTC, sblondeau commented on src/Entity/Contact.php
> +     * @Assert\Length(max="255")
ajouter Assert\Email

2021-01-06 19:35 UTC, sblondeau commented on src/Entity/Contact.php
> +     * @Assert\Regex(pattern="/^[0-9]*$/", message="Seuls les caractères numériques sont autorisés.")
je mettrais meme pas ce Regex
si je veux mettre un +31 123456 parce que j'habite pas en France par ex ?

2021-01-07 10:01 UTC, AmelieRoussel approved these changes

2021-01-07 13:28 UTC, sblondeau approved these changes

2021-01-07 13:28 UTC, merged